name: Clone list of Global variables

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs: 
      source_data: 
        type: string
        required: true
        default: source_data
      dest_json:
        type: string
        required: true
        description: 'Destination Project file path'
        
jobs:
    # This workflow contains a single job called "build"
    export-globalVariableToproject:
      uses: Puru-Org/Octopus-Deploy/.github/workflows/python.yaml@main
      with: 
        source_data: ${{ github.event.inputs.source_data }}
        dest_json: ${{ github.event.inputs.dest_json }}