name: Clone list of Global variables - Pattern-2

on:
  workflow_dispatch:
    inputs:
      global_ref_json:
        description: 'Path to the JSON file containing references to global variables'
        required: true
        type: string
        default: Octopus-CD/Octopus/global_ref.json
      project_variable_json:
        description: 'Path to the destination JSON file'
        required: true
        type: string
        default: Octopus-CD/Octopus/demo-variables.json
      projectName:
        type: string 
        required: true
        description: 'Octopus Project Name'
        default: project-1
      octopus_url:
        type: string
        required: true
        default: "https://deploy1.octopus.app"
        description: 'Octopus URL'

jobs:
  export-globalVariableToproject:
    uses: Puru-Org/Octopus-Deploy/.github/workflows/consolidated_global_to_project.yaml@main
    with:
      global_ref_json: ${{ github.event.inputs.global_ref_json }}
      project_variable_json: ${{ github.event.inputs.project_variable_json }}
    secrets: inherit
  import-variables-octopusProject:
    needs: 
      - export-globalVariableToproject
    uses: Puru-Org/Octopus-Deploy/.github/workflows/addProjectVariablefromfile-final.yaml@main
    with:
      projectName: ${{ github.event.inputs.projectName }}
      octopus_url: ${{ github.event.inputs.octopus_url }}
      variableFilePath: ${{ github.event.inputs.project_variable_json }}
    secrets: inherit 

