name: Clone list of Global variables

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs: 
      global_ref_json: 
        type: string
        required: true
        default: Octopus/global_ref.json
      project_variable_json:
        type: string
        required: true
        description: 'Destination Project file path'
        default: Octopus/demo-variables.json
        
jobs:
    # This workflow contains a single job called "build"
    export-globalVariableToproject:
      uses: Puru-Org/Octopus-Deploy/.github/workflows/python.yaml@main
      with: 
        global_ref_json: ${{ github.event.inputs.global_ref_json }}
        project_variable_json: ${{ github.event.inputs.project_variable_json }}