#############################################
## Workflow to call reusable workflow from Puru-Org/Octopus-Deploy
## 
##############################################
name: Clone global variables and import to Octopus project
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs: 
      global_ref_json: 
        type: string
        required: true
        default: Octopus/global_ref.json
      project_variable_json:
        type: string
        required: true
        description: 'Destination Project file path'
        default: Octopus/variable-2.json
      projectName:
        type: string 
        required: true
        description: 'Octopus Project Name'
        default: project-1
      octopus_url:
        type: string
        required: true
        default: "https://deploy1.octopus.app"
        description: 'Octopus URL'
        
jobs:
    # This workflow contains a single job called "build"
    export-globalVariableToproject:
      uses: Puru-Org/Octopus-Deploy/.github/workflows/python-pattern2.yaml@main
      with: 
        global_ref_json: ${{ github.event.inputs.global_ref_json }}
        project_variable_json: ${{ github.event.inputs.project_variable_json }}
      secrets: inherit
    import-variables-octopusProject:
      needs: 
        - export-globalVariableToproject
      uses: Puru-Org/Octopus-Deploy/.github/workflows/addProjectVariablefromfile-pattern-3.yaml@main
      with:
        projectName: ${{ github.event.inputs.projectName }}
        octopus_url: ${{ github.event.inputs.octopus_url }}
        variableFilePath: ${{ github.event.inputs.project_variable_json }}
      secrets: inherit 
